"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-05-09 14:15:19.504904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_conflict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('target_sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('mine_data', sa.Text(), nullable=False),
    sa.Column('theirs_data', sa.Text(), nullable=False),
    sa.Column('mine_version', sa.Integer(), nullable=False),
    sa.Column('theirs_version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_conflict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_conflict_sync_uuid'), ['sync_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_sync_conflict_target_sync_uuid'), ['target_sync_uuid'], unique=False)

    op.create_table('sync_pairing_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('sync_pairing_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_pairing_tokens_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setting_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('storyline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storyline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storyline_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('sync_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('auth_token', sa.String(length=255), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token'),
    sa.UniqueConstraint('device_id')
    )
    with op.batch_alter_table('sync_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_device_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('user_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_session_sync_uuid'), ['sync_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_session_user_id'), ['user_id'], unique=False)

    op.create_table('alignment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alignment_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('arc_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'setting_id', name='uq_arc_type_name_setting')
    )
    with op.batch_alter_table('arc_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_type_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('background',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('faction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('faction_values', sa.Text(), nullable=True),
    sa.Column('faction_income_sources', sa.Text(), nullable=True),
    sa.Column('faction_expenses', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faction_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('event_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('node_type', sa.Enum('exposition', 'action', 'reaction', 'twist', 'development', 'other', name='nodetype'), nullable=False),
    sa.Column('x_position', sa.Float(), nullable=False),
    sa.Column('y_position', sa.Float(), nullable=False),
    sa.Column('storyline_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_node_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_plot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storyline_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_plot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_plot_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sights', sa.Text(), nullable=True),
    sa.Column('smells', sa.Text(), nullable=True),
    sa.Column('sounds', sa.Text(), nullable=True),
    sa.Column('feels', sa.Text(), nullable=True),
    sa.Column('tastes', sa.Text(), nullable=True),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('is_dungeon', sa.Boolean(), nullable=True),
    sa.Column('is_city', sa.Boolean(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location__sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('object_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('object_value', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(length=255), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object__sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('race',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_trait', sa.String(length=255), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('storyline_to_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storyline_id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storyline_to_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storyline_to_setting_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['sync_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_log_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('world_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_data_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('actor_age', sa.Integer(), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.Column('job', sa.Text(), nullable=True),
    sa.Column('actor_role', sa.Text(), nullable=True),
    sa.Column('alignment_id', sa.Integer(), nullable=True),
    sa.Column('ideal', sa.Text(), nullable=True),
    sa.Column('bond', sa.Text(), nullable=True),
    sa.Column('flaw', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alignment_id'], ['alignment.id'], ),
    sa.ForeignKeyConstraint(['background_id'], ['background.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('faction_a_on_b_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faction_a_id', sa.Integer(), nullable=True),
    sa.Column('faction_b_id', sa.Integer(), nullable=True),
    sa.Column('overall', sa.Text(), nullable=True),
    sa.Column('economically', sa.Text(), nullable=True),
    sa.Column('politically', sa.Text(), nullable=True),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('is_mutual', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('how_met', sa.Text(), nullable=True),
    sa.Column('shared_history', sa.Text(), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faction_a_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['faction_b_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faction_a_on_b_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faction_a_on_b_relations_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('history_faction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('role_in_event', sa.String(length=255), nullable=True),
    sa.Column('involvement_level', sa.String(length=100), nullable=True),
    sa.Column('impact_on_faction', sa.Text(), nullable=True),
    sa.Column('faction_perspective', sa.Text(), nullable=True),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_faction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_faction_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('history_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_location_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('history_object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_object_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('history_world_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('world_data_id', sa.Integer(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.ForeignKeyConstraint(['world_data_id'], ['world_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_world_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_world_data_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_arc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('arc_type_id', sa.Integer(), nullable=False),
    sa.Column('storyline_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arc_type_id'], ['arc_type.id'], ),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_arc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_arc_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('note_type', sa.Enum('what', 'why', 'how', 'when', 'where', 'other', name='notetype'), nullable=False),
    sa.Column('linked_node', sa.Integer(), nullable=False),
    sa.Column('storyline_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['linked_node'], ['litography_node.id'], ),
    sa.ForeignKeyConstraint(['storyline_id'], ['storyline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_notes_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_plot_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plot_section_type', sa.Enum('Tension Lowers', 'Tension Sustains', 'Tension Increases', 'Singular Moment', name='plotsectiontype'), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['litography_plot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_plot_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_plot_section_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_a_on_b_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_a_id', sa.Integer(), nullable=True),
    sa.Column('location_b_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('is_mutual', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('established_date', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_a_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['location_b_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_a_on_b_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_a_on_b_relations_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('government', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_city', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_city_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_city_districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_city_districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_city_districts_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_dungeon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('dangers', sa.Text(), nullable=True),
    sa.Column('traps', sa.Text(), nullable=True),
    sa.Column('secrets', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_dungeon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_dungeon_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_economic_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_a_id', sa.Integer(), nullable=True),
    sa.Column('location_b_id', sa.Integer(), nullable=True),
    sa.Column('economic_type', sa.String(length=100), nullable=True),
    sa.Column('trade_goods', sa.Text(), nullable=True),
    sa.Column('trade_volume', sa.String(length=100), nullable=True),
    sa.Column('trade_frequency', sa.String(length=100), nullable=True),
    sa.Column('trade_value', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_a_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['location_b_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_economic_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_economic_relations_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_flora_fauna',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('living_type', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_flora_fauna', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_flora_fauna_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_geographic_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_a_id', sa.Integer(), nullable=True),
    sa.Column('location_b_id', sa.Integer(), nullable=True),
    sa.Column('geographic_type', sa.String(length=100), nullable=True),
    sa.Column('distance', sa.String(length=100), nullable=True),
    sa.Column('travel_time', sa.String(length=100), nullable=True),
    sa.Column('travel_difficulty', sa.String(length=50), nullable=True),
    sa.Column('travel_method', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_a_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['location_b_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_geographic_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_geographic_relations_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_hierarchy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_location_id', sa.Integer(), nullable=True),
    sa.Column('child_location_id', sa.Integer(), nullable=True),
    sa.Column('hierarchy_type', sa.String(length=100), nullable=True),
    sa.Column('parent_type', sa.String(length=50), nullable=True),
    sa.Column('child_type', sa.String(length=50), nullable=True),
    sa.Column('administrative_level', sa.Integer(), nullable=True),
    sa.Column('governance_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['parent_location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_hierarchy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_hierarchy_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_political_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_a_id', sa.Integer(), nullable=True),
    sa.Column('location_b_id', sa.Integer(), nullable=True),
    sa.Column('political_type', sa.String(length=100), nullable=True),
    sa.Column('treaty_name', sa.String(length=255), nullable=True),
    sa.Column('treaty_date', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_a_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['location_b_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_political_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_political_relations_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('location_to_faction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('faction_presence', sa.Float(), nullable=True),
    sa.Column('faction_power', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('control_type', sa.String(length=100), nullable=True),
    sa.Column('control_strength', sa.Integer(), nullable=True),
    sa.Column('control_method', sa.Text(), nullable=True),
    sa.Column('resources_benefits', sa.Text(), nullable=True),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('established_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('local_opposition', sa.Text(), nullable=True),
    sa.Column('key_supporters', sa.Text(), nullable=True),
    sa.Column('control_mechanisms', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_to_faction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_to_faction_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('node_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('output_node_id', sa.Integer(), nullable=False),
    sa.Column('input_node_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['input_node_id'], ['litography_node.id'], ),
    sa.ForeignKeyConstraint(['output_node_id'], ['litography_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('node_connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_connection_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('sub_race',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_race_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_race_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('actor_a_on_b_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_a_id', sa.Integer(), nullable=True),
    sa.Column('actor_b_id', sa.Integer(), nullable=True),
    sa.Column('overall', sa.String(), nullable=True),
    sa.Column('economically', sa.String(), nullable=True),
    sa.Column('power_dynamic', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('is_mutual', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('how_met', sa.Text(), nullable=True),
    sa.Column('shared_history', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=255), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_a_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['actor_b_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor_a_on_b_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_a_on_b_relations_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('actor_to_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('training_location', sa.String(length=255), nullable=True),
    sa.Column('mentor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor_to_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_to_class_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('actor_to_race',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('sub_race_id', sa.Integer(), nullable=True),
    sa.Column('heritage_strength', sa.Integer(), nullable=True),
    sa.Column('cultural_upbringing', sa.Text(), nullable=True),
    sa.Column('community_standing', sa.String(length=100), nullable=True),
    sa.Column('heritage_secrets', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.ForeignKeyConstraint(['sub_race_id'], ['sub_race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor_to_race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_to_race_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('actor_to_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('proficiency_level', sa.Integer(), nullable=True),
    sa.Column('how_learned', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('practice_frequency', sa.String(length=100), nullable=True),
    sa.Column('skill_applications', sa.Text(), nullable=True),
    sa.Column('learning_goals', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor_to_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_to_skills_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('actor_to_stat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('stat_id', sa.Integer(), nullable=True),
    sa.Column('stat_value', sa.Integer(), nullable=True),
    sa.Column('base_value', sa.Integer(), nullable=True),
    sa.Column('modifier', sa.Integer(), nullable=True),
    sa.Column('temporary_modifier', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor_to_stat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_to_stat_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('arc_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arc_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emotional_state', sa.String(length=500), nullable=True),
    sa.Column('character_relationships', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('internal_conflict', sa.Text(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arc_id'], ['litography_arc.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['litography_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arc_point', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_point_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('arc_to_actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('arc_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['arc_id'], ['litography_arc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arc_to_actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_to_actor_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('arc_to_node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('arc_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arc_id'], ['litography_arc.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['litography_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arc_to_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_to_node_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('faction_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=255), nullable=True),
    sa.Column('relative_power', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('membership_status', sa.String(length=100), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('loyalty', sa.Integer(), nullable=True),
    sa.Column('join_date', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('how_joined', sa.Text(), nullable=True),
    sa.Column('reputation_within', sa.Integer(), nullable=True),
    sa.Column('personal_goals', sa.Text(), nullable=True),
    sa.Column('conflicts', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faction_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faction_members_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('history_actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('role_in_event', sa.String(length=255), nullable=True),
    sa.Column('involvement_level', sa.String(length=100), nullable=True),
    sa.Column('impact_on_character', sa.Text(), nullable=True),
    sa.Column('character_perspective', sa.Text(), nullable=True),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_actor_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_node_to_plot_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('litography_plot_section_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['litography_plot_section_id'], ['litography_plot_section.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['litography_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_node_to_plot_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_node_to_plot_section_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_actor_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('background_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['background_id'], ['background.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_background', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_background_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_class', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_class_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_faction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_faction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_faction_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_history_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_location_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object_.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_object_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_race_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_skills_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_sub_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('sub_race_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.ForeignKeyConstraint(['sub_race_id'], ['sub_race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_sub_race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_sub_race_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('litography_note_to_world_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('world_data_id', sa.Integer(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['litography_notes.id'], ),
    sa.ForeignKeyConstraint(['world_data_id'], ['world_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('litography_note_to_world_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_litography_note_to_world_data_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('object_to_owner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('ownership_type', sa.String(length=100), nullable=True),
    sa.Column('acquisition_method', sa.Text(), nullable=True),
    sa.Column('acquisition_date', sa.String(length=50), nullable=True),
    sa.Column('ownership_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_public_knowledge', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('item_condition', sa.String(length=100), nullable=True),
    sa.Column('usage_frequency', sa.String(length=100), nullable=True),
    sa.Column('storage_location', sa.Text(), nullable=True),
    sa.Column('acquisition_story', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('object_to_owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_to_owner_sync_uuid'), ['sync_uuid'], unique=True)

    op.create_table('residents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('residency_type', sa.String(length=100), nullable=True),
    sa.Column('residency_status', sa.String(length=50), nullable=True),
    sa.Column('move_in_date', sa.String(length=50), nullable=True),
    sa.Column('housing_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_public_knowledge', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('reason_for_living', sa.Text(), nullable=True),
    sa.Column('living_conditions', sa.Text(), nullable=True),
    sa.Column('relationships_neighbors', sa.Text(), nullable=True),
    sa.Column('future_plans', sa.Text(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location_.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_residents_sync_uuid'), ['sync_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_residents_sync_uuid'))

    op.drop_table('residents')
    with op.batch_alter_table('object_to_owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_to_owner_sync_uuid'))

    op.drop_table('object_to_owner')
    with op.batch_alter_table('litography_note_to_world_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_world_data_sync_uuid'))

    op.drop_table('litography_note_to_world_data')
    with op.batch_alter_table('litography_note_to_sub_race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_sub_race_sync_uuid'))

    op.drop_table('litography_note_to_sub_race')
    with op.batch_alter_table('litography_note_to_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_skills_sync_uuid'))

    op.drop_table('litography_note_to_skills')
    with op.batch_alter_table('litography_note_to_race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_race_sync_uuid'))

    op.drop_table('litography_note_to_race')
    with op.batch_alter_table('litography_note_to_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_object_sync_uuid'))

    op.drop_table('litography_note_to_object')
    with op.batch_alter_table('litography_note_to_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_location_sync_uuid'))

    op.drop_table('litography_note_to_location')
    with op.batch_alter_table('litography_note_to_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_history_sync_uuid'))

    op.drop_table('litography_note_to_history')
    with op.batch_alter_table('litography_note_to_faction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_faction_sync_uuid'))

    op.drop_table('litography_note_to_faction')
    with op.batch_alter_table('litography_note_to_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_class_sync_uuid'))

    op.drop_table('litography_note_to_class')
    with op.batch_alter_table('litography_note_to_background', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_background_sync_uuid'))

    op.drop_table('litography_note_to_background')
    with op.batch_alter_table('litography_note_to_actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_note_to_actor_sync_uuid'))

    op.drop_table('litography_note_to_actor')
    with op.batch_alter_table('litography_node_to_plot_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_node_to_plot_section_sync_uuid'))

    op.drop_table('litography_node_to_plot_section')
    with op.batch_alter_table('history_actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_actor_sync_uuid'))

    op.drop_table('history_actor')
    with op.batch_alter_table('faction_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faction_members_sync_uuid'))

    op.drop_table('faction_members')
    with op.batch_alter_table('arc_to_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_to_node_sync_uuid'))

    op.drop_table('arc_to_node')
    with op.batch_alter_table('arc_to_actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_to_actor_sync_uuid'))

    op.drop_table('arc_to_actor')
    with op.batch_alter_table('arc_point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_point_sync_uuid'))

    op.drop_table('arc_point')
    with op.batch_alter_table('actor_to_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_to_stat_sync_uuid'))

    op.drop_table('actor_to_stat')
    with op.batch_alter_table('actor_to_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_to_skills_sync_uuid'))

    op.drop_table('actor_to_skills')
    with op.batch_alter_table('actor_to_race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_to_race_sync_uuid'))

    op.drop_table('actor_to_race')
    with op.batch_alter_table('actor_to_class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_to_class_sync_uuid'))

    op.drop_table('actor_to_class')
    with op.batch_alter_table('actor_a_on_b_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_a_on_b_relations_sync_uuid'))

    op.drop_table('actor_a_on_b_relations')
    with op.batch_alter_table('sub_race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_race_sync_uuid'))

    op.drop_table('sub_race')
    with op.batch_alter_table('node_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_connection_sync_uuid'))

    op.drop_table('node_connection')
    with op.batch_alter_table('location_to_faction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_to_faction_sync_uuid'))

    op.drop_table('location_to_faction')
    with op.batch_alter_table('location_political_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_political_relations_sync_uuid'))

    op.drop_table('location_political_relations')
    with op.batch_alter_table('location_hierarchy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_hierarchy_sync_uuid'))

    op.drop_table('location_hierarchy')
    with op.batch_alter_table('location_geographic_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_geographic_relations_sync_uuid'))

    op.drop_table('location_geographic_relations')
    with op.batch_alter_table('location_flora_fauna', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_flora_fauna_sync_uuid'))

    op.drop_table('location_flora_fauna')
    with op.batch_alter_table('location_economic_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_economic_relations_sync_uuid'))

    op.drop_table('location_economic_relations')
    with op.batch_alter_table('location_dungeon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_dungeon_sync_uuid'))

    op.drop_table('location_dungeon')
    with op.batch_alter_table('location_city_districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_city_districts_sync_uuid'))

    op.drop_table('location_city_districts')
    with op.batch_alter_table('location_city', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_city_sync_uuid'))

    op.drop_table('location_city')
    with op.batch_alter_table('location_a_on_b_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_a_on_b_relations_sync_uuid'))

    op.drop_table('location_a_on_b_relations')
    with op.batch_alter_table('litography_plot_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_plot_section_sync_uuid'))

    op.drop_table('litography_plot_section')
    with op.batch_alter_table('litography_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_notes_sync_uuid'))

    op.drop_table('litography_notes')
    with op.batch_alter_table('litography_arc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_arc_sync_uuid'))

    op.drop_table('litography_arc')
    with op.batch_alter_table('history_world_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_world_data_sync_uuid'))

    op.drop_table('history_world_data')
    with op.batch_alter_table('history_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_object_sync_uuid'))

    op.drop_table('history_object')
    with op.batch_alter_table('history_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_location_sync_uuid'))

    op.drop_table('history_location')
    with op.batch_alter_table('history_faction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_faction_sync_uuid'))

    op.drop_table('history_faction')
    with op.batch_alter_table('faction_a_on_b_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faction_a_on_b_relations_sync_uuid'))

    op.drop_table('faction_a_on_b_relations')
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_sync_uuid'))

    op.drop_table('actor')
    with op.batch_alter_table('world_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_data_sync_uuid'))

    op.drop_table('world_data')
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_log_sync_uuid'))

    op.drop_table('sync_log')
    with op.batch_alter_table('storyline_to_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storyline_to_setting_sync_uuid'))

    op.drop_table('storyline_to_setting')
    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_sync_uuid'))

    op.drop_table('stat')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_sync_uuid'))

    op.drop_table('skills')
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_sync_uuid'))

    op.drop_table('race')
    with op.batch_alter_table('object_', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object__sync_uuid'))

    op.drop_table('object_')
    with op.batch_alter_table('location_', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location__sync_uuid'))

    op.drop_table('location_')
    with op.batch_alter_table('litography_plot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_plot_sync_uuid'))

    op.drop_table('litography_plot')
    with op.batch_alter_table('litography_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_litography_node_sync_uuid'))

    op.drop_table('litography_node')
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_sync_uuid'))

    op.drop_table('history')
    with op.batch_alter_table('faction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faction_sync_uuid'))

    op.drop_table('faction')
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_sync_uuid'))

    op.drop_table('class')
    with op.batch_alter_table('background', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_sync_uuid'))

    op.drop_table('background')
    with op.batch_alter_table('arc_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_type_sync_uuid'))

    op.drop_table('arc_type')
    with op.batch_alter_table('alignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alignment_sync_uuid'))

    op.drop_table('alignment')
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_session_sync_uuid'))
        batch_op.drop_index(batch_op.f('ix_user_session_session_id'))

    op.drop_table('user_session')
    with op.batch_alter_table('sync_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_device_sync_uuid'))

    op.drop_table('sync_device')
    with op.batch_alter_table('storyline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storyline_sync_uuid'))

    op.drop_table('storyline')
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setting_sync_uuid'))

    op.drop_table('setting')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sync_uuid'))

    op.drop_table('user')
    with op.batch_alter_table('sync_pairing_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_pairing_tokens_sync_uuid'))

    op.drop_table('sync_pairing_tokens')
    with op.batch_alter_table('sync_conflict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_conflict_target_sync_uuid'))
        batch_op.drop_index(batch_op.f('ix_sync_conflict_sync_uuid'))

    op.drop_table('sync_conflict')
    # ### end Alembic commands ###
